const TYPE_COLORS={"核心工作":"#f3a6bc","运营":"#d9c4ff","AI / 系统":"#a5ddd0","沟通":"#ffd4b8","生活":"#efe8c2","休息":"#ddd7e6"};
const PRODUCTIVE_TYPES=new Set(["核心工作","运营","AI / 系统","沟通"]);
const DEFAULT_TASKS=[{text:"",done:false},{text:"",done:false},{text:"",done:false}];
const MOTIVATIONS=["先记第一笔，今天就不是一团雾啦 ✨","一点点也算前进，今天不是空白页 🌸","先把时间看见，专注就更容易发生 💗","不是追求完美，是把今天慢慢收回来 🌷","做过的事情被看见，心里会更稳一点 🍓"];
const $=s=>document.querySelector(s);
const fmtDate=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const parseDate=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const addDays=(dateStr,n)=>{const d=parseDate(dateStr);d.setDate(d.getDate()+n);return fmtDate(d)};
const keyFor=d=>"focus-plan-day-"+d; const settingsKey='focus-plan-settings'; const legacyKeys=['adhd-day-','focus-day-'];
function loadDay(dateStr){
  let data=localStorage.getItem(keyFor(dateStr));
  if(!data){ for(const prefix of legacyKeys){ const old=localStorage.getItem(prefix+dateStr); if(old){ try{ const parsed=JSON.parse(old); const migrated={tasks:Array.isArray(parsed.tasks)?parsed.tasks.map(t=>typeof t==='string'?{text:t,done:false}:t).slice(0,3):DEFAULT_TASKS,records:Array.isArray(parsed.records)?parsed.records:[]}; while(migrated.tasks.length<3)migrated.tasks.push({text:'',done:false}); localStorage.setItem(keyFor(dateStr),JSON.stringify(migrated)); return migrated;}catch(e){} } } }
  let parsed={tasks:[...DEFAULT_TASKS],records:[]}; try{ if(data) parsed=JSON.parse(data);}catch(e){}
  if(!Array.isArray(parsed.tasks)) parsed.tasks=[...DEFAULT_TASKS];
  parsed.tasks=parsed.tasks.map(t=>typeof t==='string'?{text:t,done:false}:{text:(t&&t.text)||'',done:!!(t&&t.done)}).slice(0,3); while(parsed.tasks.length<3) parsed.tasks.push({text:'',done:false});
  if(!Array.isArray(parsed.records)) parsed.records=[]; return parsed;
}
function saveDay(dateStr,state){localStorage.setItem(keyFor(dateStr),JSON.stringify(state));}
function loadSettings(){const defaults={sleepTime:'23:00',goalHours:8}; try{const s=JSON.parse(localStorage.getItem(settingsKey)||'{}'); return {...defaults,...s}}catch(e){return defaults}}
function saveSettings(s){localStorage.setItem(settingsKey,JSON.stringify(s));}
let settings=loadSettings(); let currentDate=fmtDate(new Date()); let state=loadDay(currentDate);
function getGoalMinutes(){return Math.max(60,Math.min(16*60,Math.round((Number(settings.goalHours)||8)*60)))}
function productiveMinutes(){return state.records.reduce((sum,r)=>PRODUCTIVE_TYPES.has(r.type)?sum+Number(r.minutes||0):sum,0)}
function totalsByType(){const out={}; Object.keys(TYPE_COLORS).forEach(k=>out[k]=0); state.records.forEach(r=>out[r.type]=(out[r.type]||0)+Number(r.minutes||0)); return out}
function productiveBreakdown(){const totals=totalsByType(); const entries=Object.entries(totals).filter(([k,v])=>PRODUCTIVE_TYPES.has(k)&&v>0); return Object.fromEntries(entries)}
function taskDoneCount(){return state.tasks.filter(t=>t.done).length}
function formatHumanMinutes(min){const h=Math.floor(min/60),m=min%60; if(h&&m)return `${h}h ${m}m`; if(h)return `${h}h`; return `${m}m`}
function countdownText(){const now=new Date(); const [hh,mm]=settings.sleepTime.split(':').map(Number); const target=new Date(); target.setHours(hh,mm,0,0); const ms=target-now; if(ms<=0){$('#countdown').textContent='今天已收尾'; $('#daySub').textContent='结束时间已过，今晚就温柔收工吧。'; return;} const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000); $('#countdown').textContent=`${h}小时 ${m}分`; const leftProd=Math.max(0,getGoalMinutes()-productiveMinutes()); $('#daySub').textContent=`距离 ${settings.sleepTime} 还剩这些时间；离今天目标还差 ${formatHumanMinutes(leftProd)}。`;}
function renderTasks(){const box=$('#taskList'); box.innerHTML=state.tasks.map((task,i)=>`<div class="task ${task.done?'done':''}" data-index="${i}"><div class="task-num">${i+1}</div><input class="task-text" type="text" value="${escapeHtml(task.text)}" placeholder="例如：广告复盘" /><button class="task-check ${task.done?'done':''}" type="button" aria-label="完成"></button></div>`).join(''); box.querySelectorAll('.task').forEach(row=>{const i=Number(row.dataset.index); row.querySelector('.task-text').addEventListener('input',e=>{state.tasks[i].text=e.target.value; saveDay(currentDate,state); renderFocusBadge();}); row.querySelector('.task-check').addEventListener('click',()=>{state.tasks[i].done=!state.tasks[i].done; saveDay(currentDate,state); renderTasks(); renderFocusBadge();});});}
function renderFocusBadge(){$('#focusBadge').textContent=`主任务 ${taskDoneCount()} / 3`;}
function renderPieAndLegend(){const breakdown=productiveBreakdown(); const used=productiveMinutes(); const cap=getGoalMinutes(); const pct=Math.min(100,used/cap*100); $('#doneHours').textContent=(used/60).toFixed(1)+'h'; $('#progressBar').style.width=pct+'%'; $('#progressText').textContent=Math.round(pct)+'%'; $('#goalText').textContent=`目标 ${settings.goalHours}h`; let acc=0,stops=[]; Object.entries(breakdown).sort((a,b)=>b[1]-a[1]).forEach(([name,min])=>{if(min<=0||acc>=cap)return; const start=acc/cap*100; acc+=Math.min(min,Math.max(0,cap-acc)); const end=acc/cap*100; stops.push(`${TYPE_COLORS[name]} ${start}% ${end}%`);}); if(acc<cap) stops.push(`var(--free) ${acc/cap*100}% 100%`); $('#pie').style.background=`conic-gradient(${stops.join(',')})`; const legend=$('#legend'); const totals=totalsByType(); const productiveRows=Object.entries(totals).filter(([k,v])=>PRODUCTIVE_TYPES.has(k)&&v>0).sort((a,b)=>b[1]-a[1]); legend.innerHTML=productiveRows.length?productiveRows.map(([n,m])=>`<div class="legend-row"><span class="legend-left"><span class="dot" style="background:${TYPE_COLORS[n]}"></span>${n}</span><strong>${(m/60).toFixed(1)}h</strong></div>`).join(''):'<div class="empty">还没有有效产出记录。先记一笔小小完成也可以。</div>'; const nonProd=Object.entries(totals).filter(([k,v])=>!PRODUCTIVE_TYPES.has(k)&&v>0).sort((a,b)=>b[1]-a[1]); const msg=used===0?MOTIVATIONS[0]:used>=cap?'今天有效产出已经达标啦！做得很好 🌟':`已完成 ${formatHumanMinutes(used)} 有效产出；生活/休息已记录，但不算进目标。`; $('#motivate').textContent=msg + (nonProd.length?` 今天也记录了 ${nonProd.map(([n,m])=>`${n}${formatHumanMinutes(m)}`).join('、')}。`:'' );}
function renderRecords(){const list=[...state.records].reverse(); $('#records').innerHTML=list.length?list.map((r,idx)=>{const realIndex=state.records.length-1-idx; return `<div class="record"><div class="record-time">${escapeHtml(r.time||'')}</div><div><div class="record-title">${escapeHtml(r.what)}</div><div class="record-meta">${escapeHtml(r.type)} · ${r.minutes} 分钟</div></div><button class="record-del" data-index="${realIndex}" type="button">删除</button></div>`}).join(''):'<div class="empty">你今天做过的事情会按顺序出现在这里，慢慢把一天收回来。</div>'; document.querySelectorAll('.record-del').forEach(btn=>btn.addEventListener('click',()=>{state.records.splice(Number(btn.dataset.index),1); saveDay(currentDate,state); renderAll();}));}
function renderHistory(){const today=fmtDate(new Date()); $('#viewingDate').textContent=currentDate===today?'今天':currentDate; const rows=[]; for(let i=6;i>=0;i--){const d=addDays(currentDate,-i); const dayState=loadDay(d); const prod=dayState.records.reduce((sum,r)=>PRODUCTIVE_TYPES.has(r.type)?sum+Number(r.minutes||0):sum,0); const pct=Math.min(100,prod/getGoalMinutes()*100); rows.push({date:d,prod,pct});} $('#daysSummary').innerHTML=rows.map(r=>`<div class="day-row"><strong>${r.date.slice(5)}</strong><div class="bar-bg"><div style="width:${r.pct}%"></div></div><span>${(r.prod/60).toFixed(1)}h</span></div>`).join('');}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function download(name,text,type){const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),500);}
function exportJsonData(){const all={}; Object.keys(localStorage).filter(k=>k.startsWith('focus-plan-day-')).forEach(k=>all[k]=JSON.parse(localStorage.getItem(k))); const payload={version:2,exportedAt:new Date().toISOString(),settings,data:all}; download(`专注计划-备份-${currentDate}.json`,JSON.stringify(payload,null,2),'application/json');}
function importJsonFile(file){const reader=new FileReader(); reader.onload=()=>{try{const payload=JSON.parse(reader.result); if(payload.settings){settings={...settings,...payload.settings}; saveSettings(settings);} if(payload.data&&typeof payload.data==='object'){Object.entries(payload.data).forEach(([k,v])=>{if(k.startsWith('focus-plan-day-')) localStorage.setItem(k,JSON.stringify(v));});} state=loadDay(currentDate); $('#sleepTime').value=settings.sleepTime; $('#goalHours').value=settings.goalHours; renderAll(); alert('导入成功');}catch(e){alert('导入失败，请检查 JSON 文件。');}}; reader.readAsText(file);}
function renderAll(){ $('#todayDate').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'short'}); renderTasks(); renderFocusBadge(); renderPieAndLegend(); renderRecords(); renderHistory(); countdownText(); }
$('#sleepTime').value=settings.sleepTime; $('#goalHours').value=settings.goalHours;
$('#sleepTime').addEventListener('change',e=>{settings.sleepTime=e.target.value; saveSettings(settings); countdownText();});
$('#goalHours').addEventListener('change',e=>{settings.goalHours=Math.max(1,Math.min(16,Number(e.target.value)||8)); e.target.value=settings.goalHours; saveSettings(settings); renderAll();});
$('#recordForm').addEventListener('submit',e=>{e.preventDefault(); const what=$('#what').value.trim(); const type=$('#type').value; const minutes=Math.max(1,Math.min(720,Number($('#minutes').value)||0)); if(!what||!minutes) return; const now=new Date(); state.records.push({what,type,minutes,time:now.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),createdAt:now.toISOString()}); $('#what').value=''; saveDay(currentDate,state); renderAll(); $('#what').focus();});
document.querySelectorAll('.quick').forEach(b=>b.addEventListener('click',()=>$('#minutes').value=b.dataset.min));
$('#exportJson').addEventListener('click',exportJsonData);
$('#exportCsv').addEventListener('click',()=>{const rows=[["日期","时间","类型","事项","分钟"]]; Object.keys(localStorage).filter(k=>k.startsWith('focus-plan-day-')).sort().forEach(k=>{const date=k.replace('focus-plan-day-',''); const s=loadDay(date); s.records.forEach(r=>rows.push([date,r.time||'',r.type||'',r.what||'',r.minutes||'']));}); const csv='\ufeff'+rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'); download(`专注计划-全部记录-${currentDate}.csv`,csv,'text/csv;charset=utf-8');});
$('#importJson').addEventListener('change',e=>{const file=e.target.files&&e.target.files[0]; if(file) importJsonFile(file); e.target.value='';});
$('#clearDay').addEventListener('click',()=>{if(confirm('确定清空当前日期的 3 条任务和全部记录吗？')){localStorage.removeItem(keyFor(currentDate)); state=loadDay(currentDate); renderAll();}});
$('#prevDay').addEventListener('click',()=>{currentDate=addDays(currentDate,-1); state=loadDay(currentDate); renderAll();});
$('#nextDay').addEventListener('click',()=>{currentDate=addDays(currentDate,1); state=loadDay(currentDate); renderAll();});
renderAll(); setInterval(countdownText,30000); if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
